-- MySQL Script generated by MySQL Workbench
-- Mon Apr  4 16:34:10 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema brm2_mrplow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema brm2_mrplow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brm2_mrplow` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `brm2_mrplow` ;

-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_fb_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_fb_comment` (
)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_fb_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_fb_post` (
)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_fb_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_fb_event` (
)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_fb_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_fb_likes` (
)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_tw_timeline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_tw_timeline` (
)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_tw_search`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_tw_search` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_yt_channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_yt_channel` (
)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_yt_search`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_yt_search` (
)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_yt_commentThreads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_yt_commentThreads` (
)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_fb_page_stories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_fb_page_stories` (
)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_fb_page_storytellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_fb_page_storytellers` (
)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_fb_page_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_fb_page_info` (
)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_fb_post_stories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_fb_post_stories` (
)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_fb_post_storytellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_fb_post_storytellers` (
)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_fb_page_impressions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_fb_page_impressions` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `date` DATE NULL COMMENT '',
  PRIMARY KEY (`idCategory`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_brand` (
  `idBrand` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idCategory` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `date` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`idBrand`)  COMMENT '',
  INDEX `fk_mp_brand_mp_category1_idx` (`idCategory` ASC)  COMMENT '',
  CONSTRAINT `fk_mp_brand_mp_category1`
    FOREIGN KEY (`idCategory`)
    REFERENCES `brm2_mrplow`.`mp_category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_social_network`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_social_network` (
  `idSocialNetwork` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`idSocialNetwork`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_interaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_interaction` (
  `idInteraction` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` TEXT NOT NULL COMMENT '',
  `date` DATETIME NULL COMMENT '',
  PRIMARY KEY (`idInteraction`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_brand_x_social_network`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_brand_x_social_network` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idBrand` INT NOT NULL COMMENT '',
  `idSocialNetwork` INT NOT NULL COMMENT '',
  `idInteraction` INT NOT NULL COMMENT '',
  `snID` TEXT NOT NULL COMMENT '',
  `ownedBrand` ENUM('S', 'N') NULL DEFAULT 'N' COMMENT '',
  `status` ENUM('E', 'P', 'L') NULL DEFAULT 'L' COMMENT '',
  `date` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_mp_brand_has_mp_social_network_mp_social_network1_idx` (`idSocialNetwork` ASC)  COMMENT '',
  INDEX `fk_mp_brand_has_mp_social_network_mp_brand_idx` (`idBrand` ASC)  COMMENT '',
  INDEX `fk_mp_brand_x_social_network_mp_interaction1_idx` (`idInteraction` ASC)  COMMENT '',
  CONSTRAINT `fk_mp_brand_has_mp_social_network_mp_brand`
    FOREIGN KEY (`idBrand`)
    REFERENCES `brm2_mrplow`.`mp_brand` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mp_brand_has_mp_social_network_mp_social_network1`
    FOREIGN KEY (`idSocialNetwork`)
    REFERENCES `brm2_mrplow`.`mp_social_network` (`idSocialNetwork`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mp_brand_x_social_network_mp_interaction1`
    FOREIGN KEY (`idInteraction`)
    REFERENCES `brm2_mrplow`.`mp_interaction` (`idInteraction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_report` (
  `idReport` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idBrand` INT NOT NULL COMMENT '',
  `date` DATETIME NOT NULL COMMENT '',
  `recurrence` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idReport`)  COMMENT '',
  INDEX `fk_mp_report_mp_brand1_idx` (`idBrand` ASC)  COMMENT '',
  CONSTRAINT `fk_mp_report_mp_brand1`
    FOREIGN KEY (`idBrand`)
    REFERENCES `brm2_mrplow`.`mp_brand` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_report_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_report_log` (
  `idReportLog` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idReport` INT NOT NULL COMMENT '',
  `startDate` DATETIME NOT NULL COMMENT '',
  `endDate` DATETIME NOT NULL COMMENT '',
  `date` DATETIME NOT NULL COMMENT '',
  `URL` TEXT NULL COMMENT '',
  PRIMARY KEY (`idReportLog`)  COMMENT '',
  INDEX `fk_mp_report_log_mp_report1_idx` (`idReport` ASC)  COMMENT '',
  CONSTRAINT `fk_mp_report_log_mp_report1`
    FOREIGN KEY (`idReport`)
    REFERENCES `brm2_mrplow`.`mp_report` (`idReport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_user_fb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_user_fb` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(75) NULL COMMENT '',
  `clientIdFb` TEXT NULL COMMENT '',
  `clientSecretFb` TEXT NULL COMMENT '',
  `idFb` VARCHAR(75) NULL COMMENT '',
  `date` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_token` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idUserFb` INT NOT NULL COMMENT '',
  `token` TEXT NULL COMMENT '',
  `status` ENUM('S', 'N') NULL DEFAULT 'N' COMMENT '',
  `dateUpdate` DATETIME NULL COMMENT '',
  `date` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_mp_token_mp_user_fb1_idx` (`idUserFb` ASC)  COMMENT '',
  CONSTRAINT `fk_mp_token_mp_user_fb1`
    FOREIGN KEY (`idUserFb`)
    REFERENCES `brm2_mrplow`.`mp_user_fb` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_id_temp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_id_temp` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idBrandXSocialNetwork` INT NULL COMMENT '',
  `idFbField` TEXT NULL COMMENT '',
  `typeFbField` TEXT NULL COMMENT '',
  `date` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_mp_id_temp_mp_brand_x_social_network1_idx` (`idBrandXSocialNetwork` ASC)  COMMENT '',
  CONSTRAINT `fk_mp_id_temp_mp_brand_x_social_network1`
    FOREIGN KEY (`idBrandXSocialNetwork`)
    REFERENCES `brm2_mrplow`.`mp_brand_x_social_network` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brm2_mrplow`.`mp_web`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_web` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idBrand` INT NOT NULL COMMENT '',
  `url` VARCHAR(150) NULL COMMENT '',
  `analyticsUser` VARCHAR(255) NULL COMMENT '',
  `analyticsPass` VARCHAR(255) NULL COMMENT '',
  `date` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_mp_web_mp_brand1_idx` (`idBrand` ASC)  COMMENT '',
  CONSTRAINT `fk_mp_web_mp_brand1`
    FOREIGN KEY (`idBrand`)
    REFERENCES `brm2_mrplow`.`mp_brand` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `brm2_mrplow` ;

-- -----------------------------------------------------
-- Placeholder table for view `brm2_mrplow`.`mp_view_fanpage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brm2_mrplow`.`mp_view_fanpage` (`id` INT, `snID` INT, `name` INT, `date` INT, `status` INT, `idFbField` INT, `typeFbField` INT, `dateUpdate` INT);

-- -----------------------------------------------------
-- View `brm2_mrplow`.`mp_view_fanpage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brm2_mrplow`.`mp_view_fanpage`;
USE `brm2_mrplow`;
CREATE  OR REPLACE VIEW `brm2_mrplow`.`mp_view_fanpage` AS
    SELECT 
        `brm2_mrplow`.`mp_brand_x_social_network`.`id` AS `id`,
        `brm2_mrplow`.`mp_brand_x_social_network`.`snID` AS `snID`,
        `brm2_mrplow`.`mp_brand`.`name` AS `name`,
        `brm2_mrplow`.`mp_brand_x_social_network`.`date` AS `date`,
        `brm2_mrplow`.`mp_brand_x_social_network`.`status` AS `status`,
        `brm2_mrplow`.`mp_id_temp`.`idFbField` AS `idFbField`,
        `brm2_mrplow`.`mp_id_temp`.`typeFbField` AS `typeFbField`,
        `brm2_mrplow`.`mp_id_temp`.`date` AS `dateUpdate`
    FROM
        (`brm2_mrplow`.`mp_brand_x_social_network`
        JOIN `brm2_mrplow`.`mp_id_temp` ON ((`brm2_mrplow`.`mp_id_temp`.`idBrandXSocialNetwork` = `brm2_mrplow`.`mp_brand_x_social_network`.`id`))
        JOIN `brm2_mrplow`.`mp_brand` ON ((`brm2_mrplow`.`mp_brand`.`idBrand` = `brm2_mrplow`.`mp_brand_x_social_network`.`idBrand`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `mp_brand` VALUES (1,1,'Elite','2016-03-15 14:58:58'),(2,1,'Claro Guatemala','2016-03-15 14:58:58');

INSERT INTO `mp_brand_x_social_network` VALUES (1,1,1,1,'569139909838408','S','L','2016-03-15 10:45:48'),(2,2,1,1,'303977296587','N','L','2016-03-22 17:05:45');

INSERT INTO `mp_category` VALUES (1,'Hogar','2016-03-15');

INSERT INTO `mp_id_temp` VALUES (1,2,NULL,'Posts','2016-03-22 16:50:59'),(2,2,NULL,'Comments','2016-03-22 16:51:39'),(3,2,NULL,'CommentsReply','2016-03-22 17:05:45'),(4,2,NULL,'Events','2016-03-22 17:05:45'),(5,2,NULL,'EventAttending','2016-03-22 17:05:45'),(6,2,NULL,'EventDeclined','2016-03-22 17:05:45'),(7,2,NULL,'EventNoreply','2016-03-22 17:05:45');

INSERT INTO `mp_interaction` VALUES (1,'Fanpage','2016-03-15 14:58:58');

INSERT INTO `mp_social_network` VALUES (1,'Facebook','2016-03-15');

INSERT INTO `mp_token` VALUES (1,1,'CAAGWwfOJZAp4BAMm2dM6UDT1EjAvrkttr3m7Ggo6ZCVDZBwChBgGJny6cvF7uB8AmdEAh5KD41BaSNmhqudfhljueZBZCRqsp0XJxB2afZBgGxbvbP8XPu4iex3az8myfxcxiYXypoExEdl91kXZCpyGfUZC7NZB3tvjVZBEzST5sZAoXHoCHfq0ORx','S','2016-02-23 12:19:08','2016-02-23 12:19:08');

INSERT INTO `mp_user_fb` VALUES (1,'Cristian Tangarife','256301091132754','dc897d6e5ec629a429aa39c416b506e1','100004387741316','2016-03-15 14:58:58');
